### PR TITLE
Update code to work with vapor 4

### PR DESCRIPTION
**Pull request by JaapWijnen**
I've updated the code and the example application to work with vapor 4! 
Let me know what you think, or any changes you'd like to see.
Also I've assumed the tag would be 0.4.0 for the readme (if you agree on the changes ofcourse) if this is not the case let me know

### CODE REVIEW

**Comment by JaapWijnen** [comment]
Ah unfortunately CI fails because of a swift-tools-version `5.0` vs `5.2`. Unfortunately `5.0` Isn't an option when supporting vapor 4 since it requires the platform requirement of `.v10_15` which isn't available in tools version `5.0`.

**Comment by JaapWijnen** [comment]
Is there any interest in upgrading the tools versions, or reasons to not upgrade?

**Comment by stephencelis** [comment]
Hey @JaapWijnen! Sorry for missing this. It's one of our less-trafficked repos :)

We're definitely open to updating tools versions, maybe even to 5.3! Would you like to make that change and get things merged?

**Comment by stephencelis** [comment]
We're going to merge this as-is and clean things up on `main`. Thanks!

**Pull request merged**
